#!/usr/bin/env bash

set -euo pipefail

if ! hash stow 2>/dev/null; then
  echo "stow required but not installed. Aborting."
  exit 1
fi

# Symlink packages
# ---------------------------

if [ -f "/etc/arch-release" ]; then
  packages=$(find . -maxdepth 1 -type d ! -name '.*' -printf '%f\n')
else
  # Exclude packages I don't want on non-archlinux systems
  packages=$(find . -maxdepth 1 -type d \
    ! -name '.*' \
    ! -name 'fontconfig' \
    ! -name 'gammastep' \
    ! -name 'gnome-terminal' \
    ! -name 'gtk' \
    ! -name 'i3' \
    ! -name 'i3lock' \
    ! -name 'mako' \
    ! -name 'picom' \
    ! -name 'polybar' \
    ! -name 'rofi' \
    ! -name 'sway' \
    ! -name 'waybar' \
    ! -name 'X' \
    ! -name 'xkb' \
    -printf '%f\n')
fi

for pkg in $packages; do
  stow -Rv --no-folding "$pkg" -t ~/
done
