#!/bin/sh

# Borrowed from https://github.com/Airblader

lock() {
  "$HOME/.config/i3lock/lock.sh"
}

case "$1" in
  lock)
    lock
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    systemctl suspend
    ;;
  hibernate)
    systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
    exit 2
esac

exit 0
